start devlopment of CSR interaction with sliced beam history

diff --git a/run_tests b/run_tests
--- a/run_tests
+++ b/run_tests
@@ -208,20 +208,20 @@ echo ''
 # echo '==============================================================================='
 # echo ''
 
-# testing the CSR-2D interaction
+testing the CSR-2D interaction
 
-# ./build/teufel tests/csr2d_modulated_beam.xml; rc=$?
-# if [ $rc = "0" ]
-# then
-#     echo -e "${green}return=0 - OK.${nc}"
-# else
-#     echo -e "${red}return=${rc} - Error.${nc}"
-#     num=$(($num+"1"))
-# fi
+./build/teufel tests/csr2d_modulated_beam.xml; rc=$?
+if [ $rc = "0" ]
+then
+    echo -e "${green}return=0 - OK.${nc}"
+else
+    echo -e "${red}return=${rc} - Error.${nc}"
+    num=$(($num+"1"))
+fi
 
-# echo ''
-# echo '==============================================================================='
-# echo ''
+echo ''
+echo '==============================================================================='
+echo ''
 
 if [ $num = "0" ]
 then
