removed fel1d interaction and replaced it with (non-functional) csr2d interaction

diff --git a/run_tests b/run_tests
--- a/run_tests
+++ b/run_tests
@@ -107,26 +107,43 @@ echo ''
 # echo '==============================================================================='
 # echo ''
 
-./build/teufel tests/fel_modulation.xml
-./tests/test.fel-modulation.py; rc=$?
-num=$(($num + $rc))
+# this test serves as a reference for the fel1d test case
+
+./build/teufel tests/fel_modulation.xml; rc=$?
+if [ $rc = "0" ]
+then
+    ./tests/test.fel-modulation.py; rc=$?
+    num=$(($num + $rc))
+else
+    echo -e "$red Error.$nc"
+    num=$(($num+"1"))
+fi
 
 echo ''
 echo '==============================================================================='
 echo ''
 
-./build/teufel tests/fel1d_modulation.xml
-./tests/test.fel-modulation.py; rc=$?
-num=$(($num + $rc))
+# the fel1d interaction has bee removed
+# this needs to be replaced with a crs2d test case
 
-echo ''
-echo '==============================================================================='
-echo ''
+# ./build/teufel tests/fel1d_modulation.xml; rc=$?
+# if [ $rc = "0" ]
+# then
+#     ./tests/test.fel-modulation.py; rc=$?
+#     num=$(($num + $rc))
+# else
+#     echo -e "$red Error.$nc"
+#     num=$(($num+"1"))
+# fi
+
+# echo ''
+# echo '==============================================================================='
+# echo ''
 
 if [ $num = "0" ]
 then
     echo -e "$green no errors - all tests passed.$nc"
 else
-    echo -e "$red there were " $rc " errors - some test failed!$nc"
+    echo -e "$red there were " $num " errors - some test failed!$nc"
 fi
 
